name: Compilar TFG con LuaLaTeX y BibLaTeX
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el cÃ³digo
        uses: actions/checkout@v4

      - name: Configurar dependencias
        run: sudo apt-get install biber

      - name: Compilar PDF (LuaLaTeX + Biber)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: lualatex
          args: >
            -pdf -lualatex -shell-escape -file-line-error -interaction=nonstopmode
          extra_runs: "biber"

      - name: Guardar PDF Final
        uses: actions/upload-artifact@v4
        with:
          name: TFG_Lu_Final
          path: main.pdf