name: Compilar TFG con LuaLaTeX y BibLaTeX
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar dependencias necesarias
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-luatex \
            texlive-science \
            biber

      - name: Primera corrida con LuaLaTeX
        run: lualatex -interaction=nonstopmode -halt-on-error main.tex

      - name: Procesar bibliografía con Biber
        run: biber main

      - name: Segunda y tercera corrida con LuaLaTeX
        run: |
          lualatex -interaction=nonstopmode -halt-on-error main.tex
          lualatex -interaction=nonstopmode -halt-on-error main.tex

      - name: Guardar artefacto generado
        uses: actions/upload-artifact@v4
        with:
          name: TFG_Final
          path: main.pdf